### ISSUE TITLE
Rename "normalize downmixed volume" to something easier to understand.

### ISSUE THREAD

**Issue by tru** [plexinc/plex-media-player#118]
This causes a lot of confusion, I recently saw what apple did with the apple tv and I thought it was pretty good:

They have a setting called "Sound" with two settings: "Full dynamic range" or "Reduce loud noises" which I think makes it super clear what the option does.

I think we should rename our option to something similar to that, more explanatory.

Ping @plexinc/user-experience

**Comment by tru** [comment]
Here is what apple does:

http://c.hieta.se/image/1K0U2V373V2u/Image%202015-11-01%20at%205.10.50%20PM.png

**Comment by wm4** [comment]
Sounds good to me.

**Comment by luisherrero** [comment]
Yep, I've noticed that too this weekend and I really like it. Also it sounds less cryptic than "night mode" or something like that.

**Comment by atrus05** [comment]
(side note: Isn't Night mode something different)

((side side note: Shouldn't we also add the night mode that is in there. I think we should, to get more people testing it. It is a sane feature.))

**Comment by wm4** [comment]
(I'll need to make the DRC filter filter the data after downmixing, not before to make it work well.)

**Comment by tru** [comment]
@wm4 could that explain some of the bad sounds some people have reported?

**Comment by wm4** [comment]
If you mean the comments about the DRC filter, no. From what I know, PHT does not insert a DRC filter or anything on downmix. Since we use the same coefficients for downmixing now, it should sound the same, but supposedly PMP still adds "crackling" to the audio, while PHT doesn't (with normalization disabled in both). I have no explanation for this yet.

One possibility is that it's because PHT clamps the audio to range after mixing, while PMP (libswresample) doesn't - but I have not much hope that this makes actually the difference. But we can try this too. I'm just waiting that libswsresample gets support.

**Comment by atrus05** [comment]
If you base the crackling on my old comment in the slack chat from a few weeks ago, I would consider letting more people try it. I would not say that it is crackling, just that it is borderline distortion for some channel videos that I tried. None of my normal videos (local movies) that I tried had this issue.

If you were not referring to me, then ok :)

**Comment by wm4** [comment]
Well, the point is, people are hearing a difference between PHT and PMP.

**Comment by tru** [comment]
Here is how I changed the dialog for now, the option is now called "Normalize" and the options are "Original Audio" or "Reduce Loud Noises"

Feedback on that?

![Image](http://c.hieta.se/image/130b0t143P2I/Screen%20Shot%202015-11-03%20at%2008.44.19.png)

**Comment by gitSebastian** [comment]
What i like about the above TV screen is that they don't even propose `Normalize` (which to common folks sounds awfully alike to "reduce loud noises" in practice, even if it's not the same thing) and only propose `Reduce loud noises`.

Is there a bad case for us to do "normalizing" per default and only propose "reduce loud noises" as an option? And if yes, then maybe we should also translate-to-human the `Normalize` option (to something like "Keep all audio to same loudness" or some such)?

**Comment by eithe** [comment]
For a normal user, that UI might be confusing. What have my mum set when she "chose" (from a UI perspective) Normalize -> Original Audio. Does that mean it is set to normalize the original audio? Could then "Reduce loud noises" be an extra feature of this normalize setting? I would have renamed "Original audio" to something that explains it more specifically; "Off: Keep original audio" (if you want to keep those two setting modes for it).

Imho I don't see why this can't be a simple on/off switch called "Reduce loud noises (normalize)" like I believe @gitSebastian suggested.

**Comment by TheFireKahuna** [comment]
Does Keep Original Audio basically just do clipping protection? Does that clipping protection lower the whole volume whenever a channel exceeds the threshold, or simply lower the volume of individual channels (the ones that clip) pre-mixing?

**Comment by wm4** [comment]
>Does Keep Original Audio basically just do clipping protection? Does that clipping protection lower the whole volume whenever a channel exceeds the threshold, or simply lower the volume of individual channels (the ones that clip) pre-mixing (meaning an excessive bass wont lower the entire volume)?

Not yet. All what normalization does is literally normalizing the downmix matrix, so that if all input is in range, all output will be in range as well. Of course, this reduces volume, which is what everyone is complaining about. Someone has suggested that we should put a DRC filter after the downmix, which would dynamically adjust the volume of the output. This could help, but I'm not sure if people would be fine with such automatic adjustments (they are audible).

>Additionally, the LFE channel needs to be low-pass filtered at 100/120hz, to prevent garbage in the LFE channel corrupting the mix 

We could just not mix the LFE channel. There's not much of a point to it anyway. libswresample does by default not mix the LFE channel, and I've changed it in PMP only for the sake of making it behave exactly like PHT.

**Comment by TheFireKahuna** [comment]
Sound quality would be affected by normalizing the volume and then boosting the volume right? Or are you talking about a DRC post mixing without normalization. Wouldn't that mean clipping still gets through?

Was normalization enabled by default in PHT? If not, its an option that should be off be default ideally. It does audibly effect the dynamic range of a mix, and since most people may not know what it means and never look into the option, they will by default get a narrower mix.

LFE isn't really needed in , that's true. Maybe leaving it as a toggleable option for people who absolutely cant handle a different audio to PHT. If the LFE channel is being used anywhere though (pre-mixing too), it should be low-pass filtered regardless for the formats on that list in my prior post.

**Comment by wm4** [comment]
>LFE isn't really needed in , that's true. Maybe leaving it as a toggleable option for people who absolutely cant handle a different audio to PHT.

I can try to remove the LFE mix, while keeping all other coefficients at the same ratio. I bet nobody will hear the difference, except that with LFE there will be more annoying artifacts.

**Comment by gingerbeardman** [comment]
How do I get to this Settings > Normalise menu?

**Comment by wm4** [comment]
@gingerbeardman: in the PMP main screen, click on the username on the top right corner, which should show a menu. Then click "Settings", then "Audio", then the setting should be somewhere there.

**Comment by gingerbeardman** [comment]
@wm4 thanks!
