### ISSUE TITLE
Auto-switch is sometimes triggered when seeking in transcoded video

### ISSUE THREAD

**Issue by rcombs** [plexinc/plex-media-player#121]
I've noticed the display going blank for a second when seeking, usually only the first time I seek in a file. My projector's OSD says it's switching to 60p, and then back to 24p a moment later.

**Comment by wm4** [comment]
Possible that's it's broken in the C++ host, but on the other hand it's slightly hard to handle due to web-client interaction.

**Comment by rcombs** [comment]
This still happens.

**Comment by wm4** [comment]
To explain the problem: transcode seeking is currently handled in web-client. So the host doesn't know about the seeks. When it gets a request to stop playback, it has no idea whether this is because playback should really be stopped, or if it's because the file is to be reloaded at a different playback position.

I think this should eventually be solved by moving the transcode seeking to the host. This would solve a bunch of other problems as well. But for now, we could apply a quick fix by having web-client tell us what's going on.

**Comment by wm4** [comment]
PS: and the way to do this would be modifying the player's ``stop()`` method, or adding a separate one. It would indicate whether the host should reset the display mode. Alternatively, we could give the web-client full control over display switching, but I think this would be worse.

**Comment by firasdib** [comment]
Looked into this yesterday, and from what I can tell, this behavior should occur whenever the stream is being switched when watching transcoded video. That includes changing video quality, subs and audio as well. Do we only want to prevent the display mode switch when you seek or in all scenarios?

**Comment by wm4** [comment]
I think we want to prevent it in all of these cases. The main reason we switch back at all is to make animations for normal navigation smoother. It makes no sense to switch back and then switch again after a second.

**Comment by firasdib** [comment]
If so, web can send a signal to the host (as we discussed yesterday) telling it when a stream switch is occurring so that it can handle the scenario properly. Does that work?

**Comment by wm4** [comment]
It should work.

**Comment by firasdib** [comment]
I pushed the code for web for this last week, its in the `konvergo-121-fix-display-mode-switching` branch. Did you finish up the host part of this @wm4 ?
