### ISSUE TITLE
PMP display does not fill entire screen

### ISSUE THREAD

**Issue by cynix** [plexinc/plex-media-player#134]
Compiled from source on Arch Linux following instructions provided in the readme. It seems PMP will only display as 1280x720, even though the display's resolution is 1920x1080 and fullscreen is enabled.

I was able to work around this by editing the `width` and `height` properties of `KonvergoWindow` in `src/ui/webview.qml`. I'm not too familiar with Qt so I'm not sure if this is supposed to automatically adjust to fill the display or not.

**Comment by tru** [comment]
What Qt version are you using? The web view will scale when you resize with fancy content zoom inside the HTML, but it relies on a pretty new version of Qt.

**Comment by cynix** [comment]
I tried both Qt 5.6.0-alpha1(as suggested in the readme) and the latest revision of the 5.6 branch. Same result.

PMP is started with `/usr/bin/xinit /usr/local/bin/plexmediaplayer -- :0 -bs -nolisten tcp`.

**Comment by wm4** [comment]
Works for me - also on Linux.

**Comment by tru** [comment]
What happens if you run it under a window manager? I wonder if there is some resize event that doesn't come through. Also you can press ctrl+shift+d and see what sizes and scales are available under window and web section.

**Comment by cynix** [comment]
I'm running this on my HTPC and I don't have a window manager installed. I'll see if I can find one that's easy to setup…

Ctrl+Shift+D gives me:
```
Window and web
  Window size: 1280x720
  DevicePixel ratio: 1
  Web Max Height: 1440
  Web scale: 1
  Desired Scale: 1
  Zoom Factor: 1
```

Also, not sure if this is related, but it seems `QGuiApplication::focusWindow()` always returns null, causing `DisplayComponent::getApplicationDisplay()` to fail, and as a result display mode is not changed when I start playing a video.

**Comment by cynix** [comment]
OK, both scaling and `QGuiApplication::focusWindow()` appear to work if run under a window manager.

It would be nice if I could run it without a window manager though. I expect many people would run it like this on HTPCs.

**Comment by wm4** [comment]
Depends if the Qt API allows detection this situation. I'll look on Monday.

**Comment by TonioRoffo** [comment]
@cynix - I made it work without window manager on Ubuntu 14.04:

startx ./plexmediaplayer -geometry 1920x1080+0+0

Edit your resolution as needed

**Comment by normanu** [comment]
Also having this issue, putting geometry in at xinit does not fix it for me.

**Comment by hv15** [comment]
I too have been having this problem on Archlinux as of 02/04/2017 - downgrading to versions of PMP `< 1.2.4` did not help; though version `1.2.2` did work for me *before* my system upgrade. This leads me to believe that something in X server or QT has changed affecting how geometry is determined.

@TonioRoffo I'm surprised that that worked for you, as `-geometry` is a flag to xterm - what happens when you do `xinit -geometry 1920x1080+0+0 -e /usr/bin/plexmediaplayer` instead?

For me using the `-geometry` trick has not worked - *completely*. The UI is still scaled incorrectly and sized at `1280x720px`, **but** all my media plays at fullscreen resolution of `1920x1080px` (the status bar/control bar all float over the video window when visible). Could it be that the video player is using a different source for the geometry data then the UI?

When looking in [plexmediaplayer.log](https://github.com/plexinc/plex-media-player/files/888457/plexmediaplayer.log.txt) this line sticks out:

```sh
2017-04-02 16:49:03 [ DEBUG ] KonvergoWindow.cpp @ 240 - Restoring geo: QRect(0,0 -2147483648x-2147483648) 
```

**Comment by vguerci** [comment]
had the same issue, that I solved with :

    /usr/bin/xinit /usr/bin/plexmediaplayer --scale-factor 1.5

In my case, PMP debug shows a 1080p display, and a 720p window. _(1080/720=1.5)_

**Comment by wm4** [comment]
@hv15 @vguerci that's a known Qt bug - I think it is/will be fixed in Qt, but I don't know which version.
