### ISSUE TITLE
PMP playing back super low quality audio on specific channel, PHT not

### ISSUE THREAD

**Issue by atrus05** [plexinc/plex-media-player#151]
PMP version 1.0.2 (seen it in all versions I think though).
Hardware: Mac Mini
OS: OSX Yosemite

Using the TV4play channel and playing back ```Så Mycket Bättre``` for example , the audio is extremely low bitrate, as can be seen on this debug overlay:
![low audio bitrate](https://cloud.githubusercontent.com/assets/840936/11168222/044d8058-8b86-11e5-8a14-08fb5108eb29.png)
PHT however does not have this issue.
PMP log (bad audio): https://gist.github.com/atrus05/0e774d5564af2f2fdc84
PHT log (good audio): https://gist.github.com/atrus05/05ab7d2b36fb97231642
PMS log (containing playback from both PMP and PHT): https://gist.github.com/atrus05/e7baafae0466946698a8

**Comment by wm4** [comment]
It happens because playback is done via HLS. HLS has adaptive bitrate in its protocol, and FFmpeg exposes this by adding each bitrate level as separate audio track. For some reason, web-client makes mpv select track 1, and track 1 happens to be the lowest quality here. (Normally, mpv will select best quality, but this choice is overridden. It still works for video though, so the video quality is ok.)

Not so sure what happens in the PHT case.

**Comment by atrus05** [comment]
Thanks @wm4. Created a ticket in the web client repo. Closing this one.
