### ISSUE TITLE
Decide behavior when audio device init fails

### ISSUE THREAD

**Issue by wm4** [plexinc/plex-media-player#170]
If the user selects an audio device that does not work, or a once working audio device got removed or changes its ID (hotplugging or OS update), PMP will simply play video without audio. (This behavior improves user experience in other weird corner cases and is "needed".)

This is probably not very user-friendly. Should we show a warning message if the audio dies or could not be initialized?

Also, the GUI settings dialog will show a blank field for the audio device. The audio device setting itself uses the device ID, while the GUI shows the human readable description of the device. If there is no description with the appropriate ID. web-client shows a blank field for other settings too if the raw settings value does not match with any of the possible choices listed by the settings description. This should also be fixed.

CC @dogonwheels

**Comment by OttoKerner** [comment]
Windows knows the concept of a "default" audio device. Don't know whether other platform have similar concepts.

In my mind a nearly ideal behaviour (from a user perspective) would be this:
User selects a preferred audio device in the Preferences of PMP.
As long as this device is present, it gets used of course.

If the preferred device is not there anymore, PMP should drop to the "default" audio device. But it should not "forget" the preference. Because at next app start the preferred audio device might be there again.

This is a good behaviour for all those external audio interfaces (USB DACs, bluetooth headphones etc.)

An indication to the user that the default audio device is used (instead of the preferred) might be desirable.

**Comment by wm4** [comment]
Sounds possible. At least on Windows and OSX, the non-exclusive modes should be doing this already (maybe, didn't check if there's something else that change the outcome again).

**Comment by LongChair** [comment]
Closing as most likely outdated.
