### ISSUE TITLE
Add Video Calibration (like in PHT)

### ISSUE THREAD

**Issue by firasdib** [plexinc/plex-media-player#188]
Users [here](https://forums.plex.tv/discussion/199990/fr-please-bring-back-the-video-calibration-feature) have requested that the video calibration feature of the old PHT to be added into PMP.

**Comment by Massaguana** [comment]
+1 This wodd be help to fix issue #208

**Comment by tru** [comment]
How would this help with 208?

**Comment by Massaguana** [comment]
because same problems with PHT for OE, but with with PHT i can Set 50Hz and do an monitor calibration.. after this it works fine.

In PHT i do this Steps: Install PHT-OE, Setup with an PC Screen (Login, Auto Login, 50Hz), Turn Off an move the Boxy to TV. Start Up ==> Works. Now the Monitor calibration. Done...

**Comment by Massaguana** [comment]
To use my ChromeBox without view issues i must setup this:
![img_1699](https://cloud.githubusercontent.com/assets/15521791/13027599/411b7fb0-d255-11e5-964f-3241999d70c9.JPG)
![img_1700](https://cloud.githubusercontent.com/assets/15521791/13027600/411e5c9e-d255-11e5-972c-21c6e7652350.JPG)
![img_1701](https://cloud.githubusercontent.com/assets/15521791/13027601/411fb01c-d255-11e5-83eb-9c79fe54df2d.JPG)
![img_1702](https://cloud.githubusercontent.com/assets/15521791/13027602/41200918-d255-11e5-8ffd-8b871f1d81b8.JPG)
https://www.youtube.com/watch?v=KFFzGYy6s-U

**Comment by Massaguana** [comment]
News about this?

**Comment by mseeley** [comment]
Closing to limit repo to defects or active discussions.
