### ISSUE TITLE
Backslash (\) can't be use in the inputmap

### ISSUE THREAD

**Issue by sjorge** [plexinc/plex-media-player#204]
Looks like the \ key can't be used in the inputmap, probably because \ is also used to escape stuff.

https://forums.plex.tv/discussion/comment/1103456/#Comment_1103456

**Comment by wm4** [comment]
Are you sure that if the ``\`` key gets hit, PMP actually receives this as input? Some special keys might produce something unexpectedly different. Other than that, I'd expect using ``"\\"`` should work as key binding string, but I couldn't confirm it. (I actually think it should be ``"\\\\"``, since you'd need to escape once for JSON, and then again for the regex. But could it be that Qt's JSON parser is not interpreting escapes?)

**Comment by sjorge** [comment]
I'll try the `\\\\` tonight (or tomorrow depend on when I get home), I only tried `\`, `\\,` and `\\\`, but it is indeed possible that \\\\ will turn into \\ with then turns into \ for PMP.

I will report back and close this if that is the case.

**Comment by wm4** [comment]
When you test it, also check the logs and look what PMP seems to be receiving if you use the ``\`` key.

**Comment by sjorge** [comment]
Indeed `\\\\` did the trick.
