### ISSUE TITLE
Add feature for picking up a local subtitle instead of just using remote server subtitles.

### ISSUE THREAD

**Issue by tru** [plexinc/plex-media-player#221]
This was a option in PHT, you could select a subtitle from the local hard drive to use instead of just relying on what the server supplies. The use case for this is when you are streaming a video from a remote non-owned server and you just want a subtitle for the current movie.

I am kinda hesitant to add a full UI for browsing the local filesystem. I wonder if we can do something easier here, like let people drop subtitles in a specific folder and just present those or even auto-selecting based on filename or something similar.

I do appreciate some UX input on this one.

**Comment by firasdib** [comment]
I'm a bit concerned about UX for this.

Ideally, if this was me, I would want something along the lines of this:

1. In the preplay page, select subtitle by opening a file chooser and selecting the SRT file.
2. During playback, do the same as I could do in the preplay page.

However, this would require some sort of file chooser to be implemented which can't be all too complicated since it should be easy to navigate with your remote and whatnot. 

Having a "setting" (external subtitle dir) or something along the lines is workable, but it should ideally also use a file chooser (since having to type `C:\Users\foo\Desktop\blah` with your remote on the TV is terrible).

**Comment by atrus05** [comment]
I agree with @firasdib. The reason for that is because this is not only important for remote server users. It is important due to the issues that only the Plex Dance™ can solve. So count me in to a supporter of some sort of file browser.

**Comment by firasdib** [comment]
@atrus05 If we support drag and drop we still have to support a file browser, or the functionality is only going to be targeted against those with a pointer device which is clearly not going to fly :wink:. If we support a file browser, we can _then_ add drag'n'drop as a bonus (imo).

**Comment by LongChair** [comment]
closing this for now as it's not part of the plans.
