### ISSUE TITLE
Tune subtitle defaults and settings

### ISSUE THREAD

**Issue by wm4** [plexinc/plex-media-player#26]
We probably should think about our subtitle defaults, and there may be room for slightly more customization. Just filing so we don't forget.

Threads:
https://forums.plex.tv/discussion/188331/feature-req-more-subtitle-placements
https://forums.plex.tv/discussion/189333/pmp-and-subtitles

**Comment by ghenry22** [comment]
Defaults for which subtitles to display if any would be a good feature, especially where there are forced subs used just for bits of dialogue having the option to default forced to on alone would be handy.

**Comment by ledge74** [comment]
Please allow an option to fetch subtitles from the UI. (Refresh metadata)

**Comment by dupsatou** [comment]
To add to this:  The current ability to add a local subtitle to a playing video is an absolute MUST in my opinion.  We've used this feature, for example, when streaming a video from a friends server when he didn't have the subtitle support we needed for our audience.  Instead of the friend having to add the SRT file to his media we were able to do it entirely on our own and have PHT use our local file instead.

**Comment by tru** [comment]
I see like three different feature requests here:

* Fetch subtitles from the UI - should be handled by the server.
* Select a local subtitle file
* More customisation like position etc.

I am going to to consider the select a local subtitle file but not the others, so I am creating a new issue for that one: #221
