### ISSUE TITLE
UI position issues in window mode

### ISSUE THREAD

**Issue by Maxou44** [plexinc/plex-media-player#267]
Hello,

When I use Plex Media Player in Window mode, if the ratio is different than my screen ratio, I have UI problem like that :

![ui1](https://cloud.githubusercontent.com/assets/8138585/13862557/71739220-ec94-11e5-88bd-8409e639b952.png)
![ui2](https://cloud.githubusercontent.com/assets/8138585/13862558/7173c1f0-ec94-11e5-9b95-ed02ea88d48d.png)

I use PMP 1.0.6

**Comment by tru** [comment]
In 1.0.5 the UI was centered but that also did the wrong thing most of the time when you had a ultrawide display for example. In 1.0.6 this was changed because we simplified the window resizing logic to not do a lot of crazy things.

I still feel like the best solution here would be for the web-client to handle this and stretch at least the OSD to all corners. I would like @mseeley and @firasdib to weigh in on the feasibility to just adapt the OSD to non 16:9 aspect ratios.

Short term I can let the host center the UI again if we feel that's better than the web-client doing it. I would prefer to keep the window sizing stuff in the host simple since it broke on different platforms in very subtle ways before.

**Comment by mseeley** [comment]
We're in a weird hybrid place where the UI is scaled but in this case we don't really want scaling we want stretching.

> I still feel like the best solution here would be for the web-client to handle this and stretch at least the OSD to all corners.

Same here. PMP is still cornered by the UI's roots as a fixed size app.

The work I'm prototyping will do away with the UI scaling and allow the UI to reflow, above a min-size, to fit the display. We can use CSS to detect the size of the viewport and adjust the UI. Typical responsive layout stuff.

Short term re-center.

**Comment by firasdib** [comment]
Sounds good to me.
