### ISSUE TITLE
Add keyboard toggle option for audio output

### ISSUE THREAD

**Issue by pooploser** [plexinc/plex-media-player#298]
Currently there is no keyboard shortcut to toggle between audio outputs (HDMI, analog stereo, etc.).
This would be great if available to toggle from the menu, even if it's too difficult to implement during playback. One usually sets the output before playback anyway.

**Comment by wm4** [comment]
Switching during playback is possible in theory, so this should be a pure UI issue. (At least I hope so.)

**Comment by sjorge** [comment]
Audio related bindings in general are lacking, for example mute is also missing.

Is this something that could be added in keyboard.json without extra code by sending a command to mpv like we do for the other audio related commands?

**Comment by LongChair** [comment]
@markus101 : any thought about this ?

**Comment by markus101** [comment]
I feel like a keyboard shortcut would easily be ignored by most of the users, there would only be the odd one that would know about it and use it, a player setting to do it seems more reasonable to me, but I'm not sure if there is enough of a push to add it since most people wouldn't need/use it (I can see the use case of hooking your laptop to your TV and wanting it).

**Comment by pooploser** [comment]
A keyboard shortcut would mean it’s mappble to a remote button, which is
what I would use on a daily basis because I often switch outputs between
TV, HiFi or headphones.

**Comment by mseeley** [comment]
Closing out feature request without a super strong use case.
