### ISSUE TITLE
Translations for new settings

### ISSUE THREAD

**Issue by tru** [plexinc/plex-media-player#319]

**Comment by wm4** [comment]
@firasdib: ping, this should be simple. It would be good to have in the RC (if not it'll look a bit crappy).

**Comment by firasdib** [comment]
This is not trivial I'm afraid. I've mentioned this issue before but we did nothing for it.

The problem is that the settings are hard-coded in english in `settings_description.json`. Web simply takes allt he TV settings and the settings from that JSON and merges them together. The TV settings are defined in web land which means they have a translation, but the ones in PMP land do not. I'm referring to [these](https://github.com/plexinc/plex-media-player-private/blob/master/resources/settings/settings_description.json#L285-L293) settings.

What we _could_ do as a workaround is have web iterate over all the values sent in by PMP and run the translation helper on them. This will require that we manually copy over all the english versions present in the `settings_description` file into `en.manual.json` and ensure those are the same at all times.

@dogonwheels Any insight on this?

**Comment by wm4** [comment]
OK, then we might need to skip this for the next RC.

**Comment by dogonwheels** [comment]
I think the workaround you mention is pretty much all we can do - unless you think otherwise?

`settings_description.json` then just deals in terms of non localised keys, and we have the unfortunate cross-repo map.

**Comment by firasdib** [comment]
The only other alternative is to flip the coin entirely I believe: have the settings definitions defined in web-land and pass them over to PMP during init. That would require a larger change though.

**Comment by firasdib** [comment]
As it turns out, you have been smart and thought of all of this before hand, @dogonwheels 😉
https://github.com/plexinc/plex-web-client/blob/master/app/js/plex/konvergo/utils/KonvergoSettings.js#L154

So this looks in the table generated by `getLocalizedTitles` or directly using the `t` util. So what we can do is to use keys in the settings_description and add the keys to web with the correct translations instead. I reckon this is a better approach.

**Comment by wm4** [comment]
Done!
