### ISSUE TITLE
Expose subtitle margin setting

### ISSUE THREAD

**Issue by wm4** [plexinc/plex-media-player#357]
When playing a 16:9 video on a 4:3 screen, there will be margins on the top and bottom of the screen (black bars). Subtitles can be rendered either within the video area, or the whole screen area. The latter is the default, and means that the subtitles will be within the black bars.

While this can be controlled with a mpv.conf option, a user has requested to expose this setting in the UI. We have to decide whether it's worth to do this or not. We could also fold it into the subtitle position setting.

Froum request: https://forums.plex.tv/discussion/221557/sub-use-margins-no

**Comment by atrus05** [comment]
I am a die hard fan of having the subtitles in the black bar. But I know there are others that prefer having them in the video, (I think mainly due to them masking out the black bars when using projectors).
Personally I think adding that to the Subtitle Settings GUI sounds like a worthwhile exercise.

**Comment by wm4** [comment]
> (I think mainly due to them masking out the black bars when using projectors)

An explicit overscan setting seems more appropriate in such cases.

**Comment by sebrk** [comment]
Any news on this? Very annoying to watch movies on iPad with subtitles in the middle of the screen almost.

**Comment by wm4** [comment]
PMP doesn't run on iPad. That's another client.
