### ISSUE TITLE
Expose more video options in the player OSD.

### ISSUE THREAD

**Issue by wm4** [plexinc/plex-media-player#38]
Options that should have options in the player OSD:
- Interlace/Deinterlace
- Zoom options

**Comment by tru** [comment]
I think this is a more general problem where we should expose more of the video options in the OSD.

**Comment by tru** [comment]
@atrus05 can you imagine more options that should be exposed in the in-player OSD?

**Comment by atrus05** [comment]
It is always a balance between ease-of-use and importance. But these are the ones I think _could_ make sense:
1. Volume slider. We are now close to wrapping up showing the volume status in the notification bar at the top right. It may or may not make sense to allow the user to use a slider to change the volume in the OSD somewhere.
2. If we add Zoom (panscan), then there will be demands for keepaspect. I am not saying it is super important, but in my book it makes equally much sense to have panscan. So if we add panscan, add keepaspect as well. Even though the OCD part of myself knows that it will be used to degrade the experience for most people that uses it... there is no accounting for taste. They want this.
3. No one asks me about this without getting an answer they do not like to hear. Here are my two non-popular answers, which frankly I am obligated towards myself to tell you that I would use:
* Browse for subtitles. As long as we are going to keep going on with this subtitle system that we are using, then the frakking Plex Dance™ is going to be a part of it. We have shown no outwards _real_ interest in solving it, and it is likely due to it being down-prioritized to many other important tasks. Which everyone understands. But as long as we have that stance there is no way that I will leave this alone. We have to allow our users to NOT go through the Plex Dance™ every time this happens somehow. And the only metadata piece that hinders playback of media (thus forcing the user to go through pain while the family is sitting next to them impatiently waiting to start watching the movie/episode) is the subtitle. The only. But I have seen comments that we should not add "Browse for subtitles". Well. I do not agree. It hinders quick playback of media. It hinders happy marriages. It hinders total enjoyment of life.
* Trigger subtitle download. Yep. I went there. Well, if you read on below this I have a suggestion that is a bit out there... but maybe it could be utilized with that feature somehow. Who knows!


The-out-there-suggestion:
I know this is going to sound a bit more complicated than your original intent with your question... but how about if we allow slots of user-choosen actions? For example:
In mpv.conf or plexmediaplayer.conf we add three slots. Each slot has a name and a command. The user adds both those and then restart PMP. That will add a toggle which has the command the user added.
The obvious positive things about this way forward:
* None of the competitors have done this (yet). The only way to do this in the competitors product is to create your own skin.
* The user can choose whatever they like. Even those things that we do not even ship in our inputmaps by default due to several different reasons. For me I would add postprocessing, DRC and lavfi=[dynaudnorm=f=100] to those three user created slots as those are features that at the moment are a bit to experimental to add (I think) to the inputmaps by default, but are super important for me as a father of a 7 month old baby (the latter two at least). If I did not have a kick-ass remote then I would think this would be very high up on my wish list.

**Comment by atrus05** [comment]
@tru had apparently already opened a ticket for "Browse for Subtitles": https://github.com/plexinc/plex-media-player/issues/221

**Comment by LongChair** [comment]
@markus101 : are there any plans in that area ?

**Comment by markus101** [comment]
No plans to my knowledge.

**Comment by LongChair** [comment]
Closing this for now then.
