### ISSUE TITLE
Build Instructions for Windows

### ISSUE THREAD

**Issue by deiden26** [plexinc/plex-media-player#382]
After successfully building PMP on my Mac, I would like to build it on my Windows machine. There are, however, no build instructions for Windows in the readme. Could someone update the readme to include build instructions for Windows?

Thanks

**Comment by wm4** [comment]
Although it works just like on the other platforms, Windows is the most complicated platform to build PMP on. Not sure if anyone can provide instructions any time soon.

**Comment by deiden26** [comment]
OK. While there will not be complete instructions, could you point me in the correct direction? What are the dependencies? What role does the build-windows.bat script play in the process?

Thanks,
Danny

**Comment by wm4** [comment]
The dependencies are mainly Qt and mpv. There are some more (mostly for remotes), but they're optional.

The main pain on Windows is caused by having two different compilers. mpv and ffmpg require to be compiled via mingw (because Visual Studio's C support is too bad). Qt requires to be compiled with Visual Studio (because QtWebEngine fundamentally requires it). Since Qt and PMP use C++ APIs, both Qt and PMP need to be compiled with Visual Studio aka MSVC.

So you somehow need to compile mpv on mingw (https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md might help). Then you should have a mpv-1.dll. Then you must make a Visual Studio DLL import lib. We use this: https://github.com/plexinc/plex-media-player/blob/master/scripts/make_mpv_lib.bat

Then you probably want to download Qt, a MSVC build.

Here's how we invoke cmake for PMP: https://github.com/plexinc/plex-media-player/blob/master/scripts/build-windows.bat
Unfortunately you can't use our pre-built deps for _reasons_. You'll have to make sure to point cmake to the Qt and mpv files.

**Comment by deiden26** [comment]
Thanks. I'll give it another shot this weekend.
