### ISSUE TITLE
Doesn't prevent display sleep during playback

### ISSUE THREAD

**Issue by vith** [plexinc/plex-media-player#386]
plex-media-player 1.1.3 on Arch Linux with gnome-shell 3.20.3

I have to move my mouse periodically to prevent display sleep during playback.

The APIs mentioned here may be of use https://stackoverflow.com/questions/31498114/how-to-programatically-prevent-linux-computer-from-sleeping-or-turning-on-screen/31504731#31504731

**Comment by wm4** [comment]
Do you have xdg-screensaver installed?

**Comment by vith** [comment]
Yes.

```console
❯ xdg-screensaver --version
xdg-screensaver 1.1.0 rc3
```

**Comment by wm4** [comment]
Then I'd argue xdg-screensaver is broken, and you should report this upstream.

**Comment by vith** [comment]
This works and doesn't require polling:

```shell
plexWindowID="$(xprop -name 'Plex Media Player' _NET_WM_USER_TIME_WINDOW | grep -Po '(?<=window id # )0x[0-9a-f]+')"
xdg-screensaver suspend "$plexWindowID"
```

 It uses perl to make this dbus method call:

`org.gnome.SessionManager->Inhibit($window_name, hex($window_id), $window_name, 8)`

And after using it, I can see that it's been successful like this:

```console
$ xset q|grep "DPMS is"
  DPMS is Disabled
```

`xdg-screensaver reset` is doing this:

`dbus-send --session --dest=org.gnome.ScreenSaver --type=method_call /org/gnome/ScreenSaver org.gnome.ScreenSaver.SimulateUserActivity`

Which silently fails but returns exit code 0 anyway. If I add `--print-reply` then I get:

```console
$ dbus-send --print-reply --session --dest=org.gnome.ScreenSaver --type=method_call /org/gnome/ScreenSaver org.gnome.ScreenSaver.SimulateUserActivity
Error org.freedesktop.DBus.Error.UnknownMethod: No such method 'SimulateUserActivity'
```

It could be a bug that `xdg-screensaver` tries to use some old gnome2 API that doesn't exist anymore and doesn't tell you that it isn't working, but is there any reason not to do a proper inhibit?

The description of `reset` in the `xdg-screensaver` manpage is:

> Turns the screensaver off immediately.

That doesn't sound like what you're trying to do anyway. The description of `suspend` sounds more appropriate:

> Suspends the screensaver and monitor power management.

**Comment by tru** [comment]
Is there something we can change here easily in PMP or is it broken upstream in xdg-screensaver? I am not sure after reading through the issue above.

**Comment by wm4** [comment]
Upstream `xdg-screensaver` could be easily considered broken here. Using suspend/resume would lead to an unreliable mess, even if we'd use the dbus APIs directly.

**Comment by tru** [comment]
Alright, in that case I consider this bug closed. One thing I could see us accept is configurable support for calling a custom script instead of xdg-screensaver if you want to experiment with a script that handle dbus messages directly instead. Let us know if this sounds like a good solution (should be fairly easy to implement)

**Comment by gerwalk** [comment]
This is 2.5 years old but I'm having the exact same problem and this thread is the top Google result with no actual answer. Running Arch Linux on a Intel NUC HTPC and launching PMP directly at startup as a systemd service. The actual command that's launching it is `/usr/bin/xinit /usr/bin/plexmediaplayer --desktop --fullscreen --scale-factor=3.0 -- :0 -nolisten tcp vt1`. I obviously have the Screensaver option in Settings set to **None** (an option that's only accessible if PMP is in "TV Mode" even though this problem exists outside of TV Mode as well) but after a few minutes of watching a video and not moving the mouse or pressing a key, the screen goes black and audio stops playing, but when I move the mouse PMP re-appears and the video was still playing the whole time the screen was black.

So this ticket was closed because the problem is with `xdg-screensaver`? After 2.5 years `xdg-screensaver` is at version 1.1.3 now and.. I'm to understand it still has a bug that affects Plex Media Player? What's the fix, or workaround? I can't uninstall `xdg-utils` because it's a dependency of `mpv`, which is a dependency of PMP. I have not yet been able to find a command or setting I can apply that will prevent the screen from going black.

**Comment by gerwalk** [comment]
After doing more searching and trial and error, I found an Xorg config solution that appears to be working for me. I follow the [Arch Wiki's guide for disabling DPMS](https://wiki.archlinux.org/index.php/Display_Power_Management_Signaling).

I created (it didn't already exist): **`/etc/X11/xorg.conf.d/10-monitor.conf`**
With the following contents:
```
Section "Monitor"
    Identifier "TV"
    Option "DPMS" "false"
EndSection

Section "ServerLayout"
    Identifier "ServerLayout0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime" "0"
    Option "BlankTime" "0"
EndSection

Section "Extensions"
    Option  "DPMS" "Disable"
EndSection
```
This is probably considered a pretty heavy-handed way of preventing the screen from blanking, especially if you use Xorg for anything else besides PMP, but in my case as I mentioned above it's a HTPC dedicated to PMP. I turn the TV off or have the TV input switched to a game console when I'm not using Plex so not having built-in screen blanking *at all* is not a problem.

I've been testing this fix for a little over an hour now and have not been able to recreate the issue. I hope this helps anybody else who comes across this thread.

**Comment by solson** [comment]
I have this problem (Plex Media Player doesn't prevent the monitor from going to sleep) and unfortunately I use it on my desktop PC, so forcing the monitor on permanently is not a solution I can reasonably use. While watching anything, I have to occasionally remind the machine I'm still there. All other video players, like VLC or mpv, correctly disable monitor sleep while they are running.

**Comment by Markieta** [comment]
I wrote a simple [script](https://gist.github.com/Markieta/e5330978a057cc3ac56ecf1ce1636242) as a workaround to prevent display/system sleep only when `plexmediaplayer` is running.

You can run this script via keyboard shortcut or even replace the `Exec` of your PMP desktop entry (mine was in: `/usr/share/applications/plexmediaplayer.desktop`).
