### ISSUE TITLE
Build instructions for Raspberry (arm architecture)

### ISSUE THREAD

**Issue by henry-spanka** [plexinc/plex-media-player#403]
Hi,
I have tried the image for embedded systems unfortunately LibreELEC lacks some features as I want to run several things in the background. Would it be possible to add build instructions for ARM? When trying to build it with the Linux instructions I get an error from your nightlies.plex.tv server that dependencies could not be found while downloading a distro hash file.

Thanks
Henry

**Comment by tru** [comment]
You need to have all dependencies built, including Qt then you pass `QTROOT´ to the folder where Qt is installed and the dependency download is going to not be executed at all.

If you manage to get it built you can post build instructions and I will merge them. I don't think anyone of us has actually done it enough to know since we mostly use the LE distribution instead.

I will close this issue since it's not something we will handle internally, but feel free to open a PR if you can verify and contribute build instructions.
