### ISSUE TITLE
WeTek Hub TodoList

### ISSUE THREAD

**Issue by LongChair** [plexinc/plex-media-player#407]
Here is a summuary of the remaining issues for Wetek Hub support
- [ ] Add enventual missing decoders aside already implemented H264, HEVC/H265, MPEG4, VC1
- [ ] implement subtitles
- [ ] implement cropping
- [ ] CleanUp mpv code vo for AML & PR to upstream
- [ ] Cleanup ffmpeg aml hardware decoders code & PR to upstream
- [x] Find out why all the audio gets downmixed to stereo
- [x] Address fc-cache generation one LE for aarch64.
- [x] implement 1080p GUI upscaling for 4k native resolutions.
- [x] Fix LIRC / MCE remote support.
- [ ] Eventually look for HW jpeg decoding for webengine.

**Comment by LongChair** [comment]
Regarding cropping i found a way to achieve it properly 

all is needed is to set `/sys/class/video/axis` to `X1 Y1 X2 Y2`
Thenyou also need to use `/sys/class/video/screen_mode`
* `0` is normal (that is keep aspect ratio
* `1` is full stretch to the window area

Need to check with @wm4 to see where to use this properly in mpv.

**Comment by tru** [comment]
Subtitles are a pretty big one for me. There was some discussion on how to handle that but I don't remember the conclusion. Do you have a way forward on that feature?

**Comment by LongChair** [comment]
Well there are a few possibilities, not sure which oen is the bets though :

* best would be to have them rendered with OpenGL as the plumbing is already in mpv, but that seems to be an issue accoring to wm4 as we can't use OpenGL for video frames rendering (using a video layer). He said, that as mpv expects the video frame to have the video size, and that not having this would intriduce doom at several places.

* then we could use fbdev to draw subtitles. i already was able to draw to fb0. Problem is that qt also draws to fb0 thru opengl and that when both mpv & qt try to draw there it will just flicker. I dunno any way to have qt & mpv sync on drawing.

* then another option would be to use fb1 which is yet another layer. i didn't try that yet. I have read that this framebuffer layer was supposed to hold smaller things like mouse pointer and such. i'm not sure we can have fullscreen RGBA subs onto this one without changing the amount of memory allocated to this framebuffer.

**Comment by wm4** [comment]
Well, we need to draw them somehow. Currently I see the following possibilities for what to do on the lowest level (regardless of how we "access" it):
- OpenGL - this is probably slow, but could work. The device can't do video rendering at 4K, so it won't be able to do subtitles at a higher resolution either. Plus, these ARM GPUs tend to be particularly bad at taking in what libass produces.
- fbdev - we don't know yet if that exposes anything useful on the target devices.
- hardsubbing in PMS - we do this on the RPI

If we use OpenGL, we need to have a mechanism to access the GL context and being able to draw them synchronized with the video.
- Create another fbdev overly ("fb1" mentioned by longchair), and have some kludgy code to hook up the existing mpv GL subtitle renderer. We do this on the RPI (even though we apparently don't actually use it), and it's very messy. Probably will put more load on the device. On the RPI we've seen that the device works well with up to 3 fullscreen overlays (video, subtitles, GUI), but essentially breaks down with more.
- Render subtitles in the GUI/with the web browser. I think web-client should have code for this for use with other devices. Not sure if this can be used. But it would reuse the GUI's OpenGL context for rendering.
- Use opengl-cb (the mpv API which we use to render video on the same GL context as the GUI on desktop). Since we won't use OpenGL for video rendering, but opengl-cb is designed and implemented with GL video rendering in mind, this could get hacky and requires workarounds. This would use the same GL context/overlay as the GUI for subtitle rendering, and would probably be cheaper than a separate context/overlay.

**Comment by LongChair** [comment]
Some more findings from my side.

Regarding the fb1 approach, the good news was that qt was able to render on fb1 (rathe than default fb0) setting `QT_QPA_EGLFS_FB` to `/dev/fb1`. After some reseach, it seems that fb1 is intended to display small overlays, typically mouse pointer on X11. So the allocated memeory for is is very small (1 Meg) compared to normal fb0 (70 Megs).

So we could increase the amount of memory allocated to fb1, but that would require some kernel configuration patch that we want to avoid. Plus we probably don't want mpv aml to rely on some kernel patch anyways. Additionnaly this would eat up some more RAM, which we already kinda lack on Hub.

Then according to vlang suggestions above, and also with some discussion with jturcotte. I think the best way might be to have subtitles drawn by webclient. Mali on hub is way more powerfull than VideoCore, and even if it cannot handle full 4K rendering at high speed, this is more bound to memory bandwith than GPU power. I also think that such an approach could benefit RPI, for which we transcode to get a proper subtitles rendering. Personally i would try to avoid transcoding as much as possible as a bunch of users still have PMS running on NAS, which don't have any realistic transcoding capabilities, and for which transcoding is a no Go :)

**Comment by tru** [comment]
@Moussa would it be hard to get the javascript subtitle rendering enabled on certain PMP platforms? I think the easiest would be to have a flag when we load media to say that we request web-client to render subs. How complicated does that sound?

**Comment by LongChair** [comment]
@tru : why involving webclient ? could'nt we do this in our qml ?

I'm also pretty sure there are some FrameBuffer Objects we could use, or just do some OpenGL in Playercomponent if we want this to remain in C++ ?

**Comment by tru** [comment]
The web-client already have code for this, so I don't see any reason to invent the wheel again with QML.

**Comment by LongChair** [comment]
oh didn't know that. Just a thought though, from what @wm4 said, subtitles are coming to mpv as either two monochrome bitmaps for libass iirc, or as an RGBA map for the other type. if that matches what webclient expects then that could work. Just not sure how passing quite a bunch of binary data thru webchannel will behave, but we could give it a try.

**Comment by tru** [comment]
The web-client is using this: https://github.com/Arnavion/libjass so we should be good with just using that, but since using raw libass + mpv is probaby more powerful when it comes to more complex subs I would like it to be optional per platform.

**Comment by LongChair** [comment]
fc-cache for aarch64 should be fixed now :)

**Comment by LongChair** [comment]
I have worked out the 1080p GUI scaling, and this got tested by monsieurlatte.

**Comment by LongChair** [comment]
Also found the proper way to get HD audio & LPCM.
Now we need to get those bits properly integrated in mpv / ffmpeg / pmp.
Will work with wm4 to get a proper implementation.

**Comment by LongChair** [comment]
Update : LIRC & MCE support is now working, just waiting for a PR to land.

**Comment by LongChair** [comment]
Other update : Now LPCM & HD Audio Passthru works right, required some kernel cleanup upstream and also Alsa Channel Mapping implementation, which have been both merged, big thanks to kwiboo for this.

**Comment by LongChair** [comment]
not in the scope anymore

**Comment by danjames92** [comment]
So no chance for an AMLogic build ever then?

**Comment by danjames92** [comment]
This dude got it working... https://github.com/olluz/LibreELEC.tv/releases

it runs at about 10fps, any chance of a real build for amlogic devices like C2?
