### ISSUE TITLE
no way to change incorrect clock in PMP embedded

### ISSUE THREAD

**Issue by rossbeck** [plexinc/plex-media-player#408]
Using my Asus Chromebox with Intel-64 embedded build.  

It appears the NTP servers are working because the time correctly set to GMT0... but there is currently no way to set your timezone.  I live in the America/Chicago timezone, so my clock is 5 hours off since we are at -5 GMT.  I'd like to suggest an option to either choose your timezone or the ability to manually set the time.  

Here is what I did to fix this in versions 1.1.2 and earlier, but as of 1.1.3 this no longer works:

```
nano /storage/.config/autostart.sh
ln -sf /usr/share/zoneinfo/America/Chicago /var/run/localtime
chmod +x /storage/.config/autostart.sh
```

Browsing around with SSH, it appears that the timezone files are still there... we just have no way to force them or choose them.

**Comment by DieterKoblenz** [comment]
Confirmed, no way to fixe timezone.

**Comment by rossbeck** [comment]
I have just switched to openPHT. It has the ability.

**Comment by LongChair** [comment]
Hello guys,

This is a topic we are working on currently.
As of now you can ajust it only setting the TZ environment variable.

Stay tuned :)

**Comment by NKnusperer** [comment]
Any updates on this?

**Comment by evanrich** [comment]
not having this...seems like a huge oversight on the dev team for this project... I just paid 149$ to get plex pass so I could use PMP, just to find out there's no setting for timezone?   Considering it's built on Openelec, which already has this setting, why was a menu option omitted for this?

**Comment by rossbeck** [comment]
Try using OpenPHT in the meantime.  It works just fine.

**Comment by jwittlincohen** [comment]
I also ran into this issue running the Plex Media Player Embedded version on Intel hardware.  The prior instructions don't appear to work as Plex appears to ignore the system time.  Both /var/run/localtime and running "date" showed the correct timezone, but Plex continued to show GMT even after a reboot.  For what it's worth, I am also a lifetime Plex Pass member.  This seems like a pretty trivial feature to add to the UI.  At the very least, use the system time so that the old fix works again.

In the mean time, I migrated to OpenPHT, which offers a fix for this issue in the UI, as well as a number of advanced video and audio settings.

**Comment by LongChair** [comment]
Maybe have a look here https://forums.plex.tv/discussion/258958/embedded-plex-media-player-x86-64-workaround-to-reflect-the-correct-local-timezone-for-the-ui-clock

**Comment by frozenmatt** [comment]
FWIW, I have looked for a solution and nothing has worked, until I found this one:  https://forums.plex.tv/discussion/258958/embedded-plex-media-player-x86-64-workaround-to-reflect-the-correct-local-timezone-for-the-ui-clock

The bottom post worked for me on my NUC running PMP Embedded.  
e.g.
"echo 'systemctl set-environment TZ=US/Mountain' >> .config/autostart.sh"

**Comment by LongChair** [comment]
Timezone setting is still in the works but there are other reported issues for this.
Closing as there is a workaround for now.
