### ISSUE TITLE
No audio with certain type of AAC audio track

### ISSUE THREAD

**Issue by OttoKerner** [plexinc/plex-media-player#493]
PMP 1.2.2.555-d1355001
Windows 10
an external audio interface is used which is set to 96 kHz sample rate

This happens when not using 'passthrough'.

Sample file https://drive.google.com/open?id=0B7NKohkDHT4cY2gwaWlQNVhRODQ

player log https://gist.github.com/OttoKerner/b248ae3310e3fad7ce717b198d7e3f6b

mediainfo identifies the audio track as having 96kHz sample rate. 
I don't know if that is even possible.
But audio is working in Plex Web. And also in desktop players like VLC and MPC-HC.
```
Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 24 min 22 s
Bit rate mode                            : Variable
Bit rate                                 : 115 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 96.0 kHz
Frame rate                               : 93.750 FPS (1024 spf)
Compression mode                         : Lossy
Stream size                              : 20.0 MiB (8%)
Title                                    : Stereo
Language                                 : Japanese
```
Playing this file resulöts in no audio. The pmp log file gets flooded with errors 
`[ ERROR ] PlayerComponent.cpp @ 518 - ffmpeg: spdif: Wrong AAC file format`
leading to rapid log file rotation.

**Comment by wm4** [comment]
A MF issue, I've taken it to https://github.com/plexinc/plex-media-server-ffmpeg-gpl/issues/96 (no, it's not fixed yet).

>The pmp log file gets flooded with errors
[ ERROR ] PlayerComponent.cpp @ 518 - ffmpeg: spdif: Wrong AAC file format
leading to rapid log file rotation.

Ignore that. It tries to fall back to spdif, but ffmpeg's spdif aac support needs data formatted in a different way, which is why it complains about "wrong file format". I've actually removed this fallback in mpv because it makes not much sense (PMP is still on an older version).
