### ISSUE TITLE
Alt+Tab on Windows shows broken behavior

### ISSUE THREAD

**Issue by wm4** [plexinc/plex-media-player#5]
This might actually be a bug of the Windows OS compositor: while our OpenGL is fullscreened, nothing is correctly redrawn.

We need to investigate when this happens, and how to workaround it.

**Comment by wm4** [comment]
Oh, and users who hit this can try the ``Plex Media Player (DirectX)`` start menu entry. It might help; we're not sure yet.

**Comment by zl4bv** [comment]
Not only does this happen when Alt+Tabbing but when changing the focus to another window (in a multi-monitor setup).

Can't reproduce with the `Plex Media Player (DirectX)` start menu entry - as suggested might be the case.

Didn't spot any errors in the log (or anything additional being logged when alt+tabbing) but happy to provide the log if that helps.

Windows 10 Pro x64
Plex Media Player 1.0.0.5

**Comment by tru** [comment]
So this most likely has to do with how windows handles a OpenGL context then. The compositor won't rendering anything if we acquire it in full screen.

Possible solution is to go to "windowed" mode when you alt-tab or do as most games seems to be doing, hide the window when you alt-tab out of it. That might actually be the correct solutions since there is a precedent here.

**Comment by sjorge** [comment]
Probably related to the VNC issues I reported on the forum, hitting the home icon fixes it. It may just be a the same focus issue right after launching.

**Comment by wm4** [comment]
Commit b09f3222ef5f391565b6f4cc01cb1551c119697e seems to be an effective workaround. Will be included in the next release.
