### ISSUE TITLE
fullscreen/window switch broken

### ISSUE THREAD

**Issue by 7ABt6kB** [plexinc/plex-media-player#525]
When in fullscreen mode, I can press / and it switches to windowed. Pressing / again does nothing. There is no way to return from the 'web player' (windowed) to the 'media player' (fullscreen) without quitting, relaunching, and pressing the full screen icon.

**Comment by markus101** [comment]
`\` is not supported in the desktop app at this time and may not be due to conflicting with keyboard input in web app.

The shortcuts that are supported are listed here: https://support.plex.tv/hc/en-us/articles/208052807-Controlling-the-App

As long as you are on the dashboard the button to enter the TV layout is visible or any of the keyboard shortcuts listed in the support document will work.

**Comment by arcooke** [comment]
Can confirm the Fullscreen toggle button is broken on my linux client as well.  Shift+F11 does work as a temporary solution

@markus101 what do you mean by "`\` is not supported"?

**Comment by LongChair** [comment]
@arcooke : Could you tell me if that is still the case with recent builds ? 

If so could you provide a full logfile so that i can have a look ?

Thanks.

**Comment by LongChair** [comment]
Closing this due to the lack of feedback, feel free to repoen if needed.
