### ISSUE TITLE
screen tearing in menus and during playback

### ISSUE THREAD

**Issue by 7ABt6kB** [plexinc/plex-media-player#526]
browsing menus and looking at library items, the screen regularly tears at the top. playing back many files will cause the same thing. problem is not with the file (vlc plays it fine).

**Comment by gabo77** [comment]
I've got this type of issue also. There's some kind of flickering with darker "squares" of different sizes appearing for a tenth of a second regularly (happens in bursts when browsing). I have recorded the screen to show the issue but I guess it should be fairly straight forward to reproduce. If not I'll share it. I'm still mainly using Plex Web in the browser because of that, it's really an annoying issue.

Client player and OS:
`"userAgent": "PlexMediaPlayer 1.2.5.606-0b42eb77 (macosx-x86_64 10.12)"`

**Comment by Trahloc** [comment]
I don't see these issues in the menu but I get video tearing during playback / low frame rate.  The exact same file will play flawlessly in Chrome over Plex though.  1080ti and i7-6700k so not a processing power issue.  I wanted to use the PMP to avoid transcoding on my server since Chrome can't play the raw file but a tearing slide show isn't really watchable.

**Comment by LongChair** [comment]
@7ABt6kB : is that still an issue with current builds ?

**Comment by LongChair** [comment]
Closing due to the lack of feedback, feel free to reopen if needed.

**Comment by gabo77** [comment]
FYI this is no more an issue for me on recent builds.
