### ISSUE TITLE
Windows 10 Media Key Integration

### ISSUE THREAD

**Issue by aknobloch** [plexinc/plex-media-player#554]
Hey all, 

Sorry if this the wrong place for this - newbie here. In the current version of the Windows 10 Plex client, hardware media keys only work while the Plex client has active focus. When another window is active, the media key codes do not get passed to the Plex client. For example, with a keyboard that has next track, previous, play/stop buttons, these keys will only work when the Plex client has active focus.

I am currently a software development senior, looking to get my feet wet with open source contribution. I'd love to give a shot at this, but would need some help setting up my development environment if anyone is willing to help.

**Comment by wm4** [comment]
Such a contribution would be welcome.

Since we're a company, we require a CLA: https://forums.plex.tv/discussion/188192/plex-media-player-open-source-contributions-and-building-faq#latest

Building for Windows is relatively hard (especially "outside" of Plex without automatic deps), but I've attempted to describe the process here: https://forums.plex.tv/discussion/comment/1426511/#Comment_1426511

**Comment by LongChair** [comment]
@aknobloch : still planning on contributing ? :)

**Comment by aknobloch** [comment]
@LongChair as far as I'm aware, this issue was resolved in one of the newer updates to the client. I'll close this issue.
