### ISSUE TITLE
HDMI off on default

### ISSUE THREAD

**Issue by keivnkarada** [plexinc/plex-media-player#57]
I'm not 100% confident but I think it is the problem.  On default if a HDMI device isn't attached to a Raspberry Pi 2 it will not turn on HDMI.  This means if you turn off your whole system and power it on from nothing then there will be no video.  PMP should turn on HDMI regardless if a HDMI device is attached.  Rasplex is able to do this so PMP should be able to do it.

**Comment by LongChair** [comment]
Hey :)

There is no off & on state for HDMI.
I'm into sure to understand your problem here. if start RPI2 without an HDMI cable connected, then start your system, and then connect the HDMI cable, RPI will just send its output to the HDMI output.

I suspect that you are running with an AVR in between and expect that RPI will switch to the right AVR source when connecting but i'm not sure ... 

Could you please detail a bit more your setup and the steps that lead you to this unexpected situation ?

Thanks,

**Comment by keivnkarada** [comment]
I am running a AVR between the RPi and the TV.   To save power my whole AV system is on a remote control switch.  All equipment is brought up at the same time.  I have to plug/unplug my RPi2 afterwards otherwise it doesn't show any video output.

I use to run Rasplex 0.6 and it did not have this problem.

**Comment by wm4** [comment]
We did have some code to auto switch on when HDMI is plugged in, but it caused other problems. Still can be enabled with hdmi_poweron option in the config file.

**Comment by NedtheNerd** [comment]
Uncomment the line  hdmi_force_hotplug=1 in your /flash/config.txt file

This will force HDMI mode even if no HDMI monitor is detected

To edit the config.txt file you will need to make /flash writeable:

SSH into your RPi and enter:

     mount -o remount,rw /flash

Then enter:

     nano /flash/cmdline.txt

Uncomment to the line and then Ctrl + X, Y and enter.

Reboot the RPi.

**Comment by wm4** [comment]
(I thought this was uncommented by default.)

**Comment by NedtheNerd** [comment]
No, it's not, that's why people are having issues.

**Comment by tru** [comment]
What's the deal with this one? Should we change the default? @ziggimon?

**Comment by NedtheNerd** [comment]
Yes.

**Comment by tru** [comment]
Alright, I'll let @ziggimon change the default if it makes sense to him.

**Comment by ziggimon** [comment]
Set a default with: https://github.com/plexinc/OpenELEC.tv/commit/d16b57775612f1af380ced68db69beacf30f996c
