### ISSUE TITLE
Enable option for decoded audio channels to match source

### ISSUE THREAD

**Issue by millercentral** [plexinc/plex-media-player#72]
Currently when PMP decodes an audio stream it always outputs all channels defined in settings (ie, if you select 7.1 it always outputs a 7.1 LPCM stream). If the source audio track has less channels then the output, then PMP adds silence to the unused channels.

This behavior prevents AVRs with 7.1+ speaker layouts from expanding audio content to all speakers using THX Ultra, Dolby PLIIx, or other processing techniques because the AVR believes it is already receiving a 7.1 soundtrack. 

Given the assumption that an AVR will always be able to do a better (or more user controllable) job at expanding audio to the speakers attached to it, please add a "Match Source" output channels option in PMP for decoded audio that when selected decodes audio, but sends the same LPCM channels to the AVR as the original content, so that the receiver can still expand the sound field.

Without this, bitstreaming is required to take advantage of AVR capabilities, which has a distinct disadvantage when it comes to video sync.

This thread covers this (and other audio-related) topics:
http://forums.plex.tv/discussion/comment/1041587/#Comment_1041587 

Thanks!

**Comment by wm4** [comment]
You can try how well it works by selecting "Auto Select Channels" for the "Channels" setting. This will try to output the audio as is, without remixing. But the OS audio API still can force it to remix, or do other undesired things to it:
- On OSX, the system dictates a single channel layout for "surround". It can be set in "Audio MIDI Setup.app". If you set it to 5.1, PMP will be forced to downmix 7.1 to 5.1. If you set it to 7.1, it's forced to upmix 5.1 to 7.1. (This happens even when using the OSX low level audio API, which we call "exclusive mode".) Hints how to influence the system-wide surround setting as changed by "Audio MIDI Setup.app" programmatically are welcome.
- On Windows, it might work if you use "exclusive mode", but I got reports that it actually depends on the Windows audio mixer surround settings. PMP will think it output 5.1 or 7.1, but actually only the stereo channels get through, and the other channels remain silent.
- I'm convinced that it works properly on RPI. Receivers typically do not accept all channel layouts as defined by HDMI, so we'd have to restrict them to a subset (for example, stereo/5.1/7.1). But the stereo vs. 5.1 vs. 7.1 case certainly should work.

So there's no clear solution, and we're still wondering what to do. We could probably improve the upmix slightly by not leaving extra channels silent.

(My own receiver has 5.1 output only, which makes testing this hard for me.)

**Comment by wm4** [comment]
Again, can you please test how much success you have with setting "Channels" to "Autoselect"?

**Comment by millercentral** [comment]
Sorry, yes. I will run some tests this weekend and report back.

**Comment by TonioRoffo** [comment]
@millercentral - I would like to add something to what OP has posted.  For 2 channel, Dolby prologic encoded material, it is of course preferable to have 2 channel output so that the receiver can do proper decoding.

However, when doing music playback, Dolby Prologic is also engaged because the receiver of course sees Plex as the same source.  For that, I would like to see a switch/option (Gui or not) so that for music library content, 2 channel audio can be sent as LPCM according to the 5.1 or 7.1 settings with silence on the remaining channels.  This way, music plays back as stereo, untouched, 2 channel movie content plays back using Prologic decoding, without touching any setting on the receiver.

As PMP is built for music & video afficionados (Audiophile has a bad ring to it...) this would be a great addition.

**Comment by wm4** [comment]
>For that, I would like to see a switch/option (Gui or not) so that for music library content, 2 channel audio can be sent as LPCM according to the 5.1 or 7.1 settings with silence on the remaining channels. This way, music plays back as stereo on the L & R channels, untouched; 2 channel movie content plays back using Prologic decoding, without touching any setting on the receiver.

If you select 5.1 or 7.1, this is what will happen currently.

Note that there are also users who would prefer the "extra" channels not to be filled with silence.

**Comment by kevinmcareavey** [comment]
Has there been any progress on this issue?

In my case, I'm running the latest PMP on a Mac Mini connected to a 5.1 AV receiver over HDMI.  In OSX, "Audio MIDI Setup.app" reports 8 channels for the receiver/HDMI (even though the receiver only supports 6 channels).  If the speaker configuration in "Audio MIDI Setup.app" is set to 7.1, then PMP will upmix (I assume it is just adding silent channels) to 7.1 regardless of whether the number of channels in PMP is set to 5.1 or 7.1.  If the speaker configuration in "Audio MIDI Setup.app" is set to 5.1, then PMP will (up)mix to 5.1 regardless of whether the number of channels in PMP is set to 5.1 or 7.1.  I've tested this with mono, stereo and 5.1 sources.  For example, PMP will report:

mono -> 5.1 (fl-fr-fc-lfe-bl-br-na-na)
stereo -> 5.1 (fl-fr-fc-lfe-bl-br-na-na)
5.1(side) -> 5.1 (fl-fr-fc-lfe-bl-br-na-na)

Here I assume "na" means that PMP is ignoring the two additional channels reported by OSX, rather than that it is outputting silence, since it reports 5.1.

Anyway, I also tried the "auto select channels" option in PMP.  In this case, PMP seems to behave correctly for audio files (stereo MP3 and FLAC) in that it will report "stereo -> stereo".  However, for video files it is inconsistent.  Some examples include: all 5.1 being handled correctly (i.e. "5.1 -> 5.1"); stereo MP3/Dolby/AAC being handled correctly (i.e. "stereo -> stereo"); mono MP3/Dolby being upmixed to stereo (i.e. "mono -> stereo"); mono/stereo DTS/FLAC being upmixed to 5.1; stereo Vorbis being upmixed to 5.1.

As @millercentral said, adding these silent channels is undesirable because it confuses the AV receiver (and me!) and prevents it from using other options such as Dolby PLII.  However, the inconsistent behaviour also makes it difficult to predict how PMP will treat source audio.  Is the "auto select channels" option intended to match input and output channels or was this just suggested as a possible workaround?

**Comment by wm4** [comment]
> Here I assume "na" means that PMP is ignoring the two additional channels reported by OSX, rather than that it is outputting silence, since it reports 5.1.

`na` means it outputs silence. If you ignore the `na` channels, you get "real" 5.1. This happens because the OSX API simply demands that we give it 8 channels for whatever reasons. My assumption is that OSX will actually discard these unused extra channels. But honestly I'm not so sure anymore.

> mono/stereo DTS/FLAC being upmixed to 5.1; stereo Vorbis being upmixed to 5.1.

Shouldn't happen. Logs?

> Is the "auto select channels" option intended to match input and output channels or was this just suggested as a possible workaround?

It is, to the extend the audio API supports it.

**Comment by wm4** [comment]
Also: does it make a difference for you whether exclusive or normal mode is used?

**Comment by kevinmcareavey** [comment]
> Also: does it make a difference for you whether exclusive or normal mode is used?

Ah.  The behaviour I described above was when exclusive mode was enabled.  However, if exclusive mode is disabled, then "auto select channels" seems to behave as expected, i.e. the input and output channels match for mono/stereo/5.1 sources.  So, the issue just seems to occur when exclusive mode is enabled.

> > mono/stereo DTS/FLAC being upmixed to 5.1; stereo Vorbis being upmixed to 5.1.
>
> Shouldn't happen. Logs?

PMP log with both exclusive mode and "auto select channels" enabled: [Plex Media Player.log.gz](https://github.com/plexinc/plex-media-player/files/361849/Plex.Media.Player.log.gz)

**Comment by wm4** [comment]
It seems to select a 8 channel output format because it provides a higher sample size:
```
 -  48000.0Hz 24bit mcpl [4][32bpp][1fbp][32bpf][8ch] int LE S (-)
 -  48000.0Hz 16bit mcpl [12][4bpp][1fbp][4bpf][2ch] int LE S packed (s16)
 -  48000.0Hz 16bit mcpl [12][16bpp][1fbp][16bpf][8ch] int LE S packed (s16)
```
So if the 24 bit format didn't exist, or if a 24 bit 2 channel format existed, it would select stereo. But since they don't exist, it decides that the 8 channel format is the best format, which causes it to select the configured multichannel layout (5.1), which causes it to upmix to 5.1 (by adding silence). Not sure if this can be fixed, maybe not.

I can't reproduce because on my system it always lists 24 bit stereo formats. I'm not sure what causes this difference. Either it's because I'm on Yosemite, or it's something about the HDMI connection.

Did you just say this case works correctly with exclusive mode disabled? Maybe we should just disable exclusive mode by default, and require the user to configure multichannel output in "Audio MIDI Setup" and make "Auto Select Channels" the default.

**Comment by kevinmcareavey** [comment]
> Did you just say this case works correctly with exclusive mode disabled?

Yes, that's correct (and thanks for the suggestion!).

It might be worth mentioning that it now looks like OSX always sends 8 channels to the AV receiver, regardless of whether PMP outputs 1.0/2.0/5.1 or whether the speaker configuration in "Audio MIDI Setup" is set to 5.1.  So the AV receiver is still confused but this seems to be the fault of OSX rather than of PMP.  I guess there's no way around this...

**Comment by wm4** [comment]
You can select the HDMI output format in "Audio MIDI Setup". Typically you can choose between 2 and 8 channels.

**Comment by wm4** [comment]
(Also: in exclusive mode PMP may change this format, while in normal mode it will not.)

**Comment by kevinmcareavey** [comment]
> You can select the HDMI output format in "Audio MIDI Setup". Typically you can choose between 2 and 8 channels.

Yeah that's what I mean.  I've selected 8 channels for HDMI in "Audio MIDI Setup" and set the speaker configuration to 5.1 so as to match my AV receiver.  However, even if PMP correctly outputs 1.0, 2.0 or 5.1 audio, the AV receiver will still think it is receiving 7.1 audio.  I'm assuming that OSX is padding the remaining channels with silence, to match the 8 channels that I was forced to select in "Audio MIDI Setup".

Ideally, if the source is 2.0, then I would want PMP to output 2.0 and I would want the AV receiver to receive 2.0 (or know that it is receiving 2.0).  This doesn't seem to be possible.

> (Also: in exclusive mode PMP may change this format, while in normal mode it will not.)

In that case, I wonder what would happen if I set "Audio MIDI Setup" to 2.0 and PMP to 5.1 in exclusive mode...
