### ISSUE TITLE
[Player] Web player track progress resumption doesn't work for tracks longer than 5 hours, 55 minutes

### ISSUE THREAD

**Issue by Alex-Richman** [plexinc/plex-media-player#738]
### Test environment
Version 1.12.3.4973
4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

### Steps to reproduce
1. Create a new library, music, enable "Store Track Progress" in advanced options.
2. Add a music track longer than 5 hours 55 minutes to the library (e.g. an audio book).
3. Play the track, skip to past 05:55:00
4. Pause the track, and close the playback bar
5. Play the track again, observe that the playback starts from the beginning rather than when you paused.

### Current behavior
1. Playback for stored progress after 05:55:00 is resumed from the start, rather than the last pause position.

### Expected behavior
1. Playback should resume from the last pause position, regardless of the time it was paused.

**Comment by Alex-Richman** [comment]
Actually seems to be somewhere between 05:52:03 and 05:52:15 that it happens.  This is for a 06:31:13 long track total.

**Comment by markus101** [comment]
What you're seeing here is the played threshold being reached when 90% of the file has been played, which is at the `05:52:05` mark.

Currently the threshold is the same same for both video and audio, which is leading to your issue and affects all clients. We're discussing splitting the threshold for audio and video, but closing this issue out as it's not a PMP issue, but comes from the server and affects all clients.

**Comment by Alex-Richman** [comment]
Ah OK, makes sense.  I think it'd be reasonable to disable the 90% playback marker for audio entirely, since audiobooks don't have the same gigantic credits that movies do and I imagine most people don't have Store Track Progress enabled for audio libraries anyway.

Alternatively instead of splitting the audio/video playback % maybe you could have a slider in advanced options for the library to change the %?

**Comment by misuchiru03** [comment]
Not just you, and the 90% track completion makes sense, and I agree about having the slider, that's a great idea. However, I have had this same issue for an audio track of any length (seemingly random--sometimes it works, most times it doesn't). Several hour-long audio track will not keep its place even if 5% of the track has been played. I think this issue has never been resolved (been an issue since dating back to 2016 doing a quick google search). It's the server side that is not storing metadata on audio tracks correctly, dumping it, or not reading it, can't tell which, even when the "Store Track Progress" is checked. The issue has existed for a great many years and never went away. I honestly don't see anyone from Plex diving in to help with this issue since it's so old and everyone is complaining about it still, unless there is a competitor of equal proportions.
