### ISSUE TITLE
Mini player doesnt work {Ubuntu 18.04

### ISSUE THREAD

**Issue by thedocHarsh** [plexinc/plex-media-player#755]
### Test environment
**PMS Version:**Version 3.53.7
**PMP Version:** Plex_Media_Player_2.12.1.871-6c71195e_x64.AppImage
**Platform (Windows/OSX/Embedded):** Ubuntu 18.04

### Steps to reproduce
1.Integrated app image in Ubuntu 18.04
2. Playback media in mini player

### Current behavior
1.When using PMP switching to mini player causes the mini player to show a thumbnail/still image while the playback continues (since audio is heard ) and when i switch back to the regular player the playback continues as usual

### Expected behavior
1.When using PMP and switching to mini player the playback should continue without problems in a smaller window (i.e. the mini player )
2. Proof / Example : Below the same video is at two diffrent timecodes (thus the mini player should be showing outright diffrent scenes)
![screenshot from 2018-06-18 13-25-18](https://user-images.githubusercontent.com/34149850/41524440-213a6168-72fb-11e8-8dfa-f1d0e35ba046.png)
![screenshot from 2018-06-18 13-25-31](https://user-images.githubusercontent.com/34149850/41524441-2165f120-72fb-11e8-9834-bc9462483b2c.png)

**Comment by mseeley** [comment]
Hi @thedocHarsh this is actually the expected behavior. It's clearly suboptimal but all the same, expected.

The video player renders video below the UI. The mini player requires the video player render above _and_ below the UI in order to render above the main application yet below the hover affordance.

It's a shortcoming of PMP. We've got cool stuff cooking to improve.
