### ISSUE TITLE
Roku Player fails on skip 10 sec command

### ISSUE THREAD

**Issue by CoolJavelin** [plexinc/plex-media-player#807]
When first starting a movie, when I press the forward button (not the fast forward) the expected behavior is to skip 10 seconds. another press, another 10 seconds.

However, many times it does a skip but returns to the beginning of the movie and cannot actually skip.

### Test environment
PMS Version 1.14.0.5470
PMP 6.1.1.5282-4907 blah, blah, blah on Roku 3700X version 8.1.0 build 4155-28
Platform Lubuntu 16.04

### Steps to reproduce
1. Press the forward  button (to the right of the OK button)

### Current behavior
1. skips for a second, then returns to beginning.

### Expected behavior
1. a 10 second skip.

Thank you,
Mark.

**Comment by OttoKerner** [comment]
This repository is for Plex Media Player. 
The Roku player is an entirely different software.

**Comment by CoolJavelin** [comment]
Oh, my bad. I will try to locate the other forum and repost there. Thanks.

**Comment by mseeley** [comment]
> However, many times it does a skip but returns to the beginning of the movie and cannot actually skip.

Hi @CoolJavelin. That definitely doesn't sound like it's working correctly. :)

Our Roku team suggested posting an issue in our forum. We'll need more information about the video(s) playing in order to figure out what could be going on. Sometimes video encoding is also problematic. Regardless, here's a good starting point for your adventure: https://forums.plex.tv/t/read-me-first-about-roku/277790.

Cheers!
