### ISSUE TITLE
PMP on Linux in 4K has a lot of flickering

### ISSUE THREAD

**Issue by nomego** [plexinc/plex-media-player#819]
When in the menues, the PMP app flickers a lot in fullscreen or windowed mode in 4K resolution.
Videos play flawlessly though (when it works, see #817 and #818).

**Comment by mseeley** [comment]
We've seen similar problems on 5K monitors. It's typically due to Qt handling of the large UI surfaces. In the past we've seen improvements when upgrading Qt, providing it more surface memory, and/or restricting the size of the surfaces created.

I'm pinging @knapsu and closing this issue out as behavior on Linux in the app image package it out of our control.

If you run into this on macOS or Windows please let us know. We'll then be able to look for ways to improve behavior while upgrading Qt next.

**Comment by nomego** [comment]
Ok so upgrading to Qt 5.11.2 didn't help.

How would one go about "providing it more surface memory" or "restricting the size of the surfaces created" @mseeley ?

**Comment by knapsu** [comment]
It was Qt `5.11.3`

**Comment by knapsu** [comment]
Oh yeah. Sorry, my mistake. Qt 5.11.3 was for Flatpak, not AppImage.

**Comment by nomego** [comment]
Oh so flatpak is upgraded as well? How can I get that one? Running `sudo flatpak update` doesn't find anything.
