### ISSUE TITLE
Remote Control API seems unstabe on Roku

### ISSUE THREAD

**Issue by alan-s-thomas** [plexinc/plex-media-player#823]
I'm trying to use the remote control API to sync some Roku clients. When I started this project everything was more or less working, but with the new PMP on Roku, I am seeing all kinds of odd items.

For this issue, let focus on an easy one. When I send a command to seek to a given timestamp, sometimes the player will respond correctly and sync to the timestamp, but sometimes it does nothing. It will always send a 200OK though.

For example if I send:

GET /player/playback/seekTo?offset=102239&type=video&commandID=61 HTTP/1.1
Host: 192.168.1.103:8324
Accept: */*
X-Plex-Client-Identifier: AT3
X-Plex-Device-Name: PHPSync

I always get back:

HTTP/1.1 200 OK
Date: Wed, 26 DEC 2018 20:17:14 GMT
Server: Plex
Connection: close
Content-Length: 0
Content-Type: text/html
Accept-Ranges: bytes

But if I look at the player, it has not changed. If I send it a few times maybe it will change, or maybe not.
below is the clients I'm sending to. V5 clients seem to work fine. V6, not so much. If I'm doing something wrong, please let me know. If you need logs or anything, just let me know how to pull them from Plex on Roku.

<Server name="Roku3" host="192.168.1.122" address="192.168.1.122" port="8324" machineIdentifier="a3de0de0ff5a860a8805620eee86b4fa" version="6.1.1.5282-4907f3688-Plex" protocol="plex" product="Plex for Roku" deviceClass="stb" protocolVersion="1" protocolCapabilities="timeline,playback,navigation,playqueues"/><Server name="Roku Stick - 2LA4CR038462" host="192.168.1.139" address="192.168.1.139" port="8324" machineIdentifier="41fdce4dd7259126568d30e7918690e3" version="5.3.10.5048-c61db7547-Plex" protocol="plex" product="Plex for Roku" deviceClass="stb" protocolVersion="1" protocolCapabilities="timeline,playback,navigation,playqueues"/>

**Comment by mseeley** [comment]
@ljunkie does this sound familiar? 

@alan-s-thomas we've got a similar user report in #805. Perhaps it's related?

I'm closing this issue out as it's related to a separate product.

**Comment by ljunkie** [comment]
@alan-s-thomas the roku webserver will return a 200 if the request was valid, and it doesn't reflect if the video player actually processed it. Is it possible the command was sent before the video was buffering? In that case, the player may simply ignore the seek. 

You may want to incorporate the `/player/timeline/poll` request to know if the video is active (ready) before sending the request to seek.

A few other things to note:
 - Always include a `X-Plex-Client-Identifier` header with the same identifier.
 - Make sure to bump the `commandID` on every new request, otherwise it may ignore the event (with a 200 response)
 - You can reset the `commandID` by hitting `/player/timeline/poll` with no `commandID` or `commandID=0` 

If you are still experiencing issues with the companion events, please open a thread in our forums and add the `roku` tag.
