### ISSUE TITLE
Delay when skipping forward or backward

### ISSUE THREAD

**Issue by humanthrope** [plexinc/plex-media-player#875]
**PMS Version:** 1.16.2.1297 (probably doesn't matter)
**PMP Version:** 2.36 or later
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Windows / OSX

### Steps to reproduce
1. Skip forward 30 seconds using the right key or back 10 seconds using the left key in any video.

### Current behavior
1. Around one second of delay before the skip happens, the buffering message briefly appears, and the video begins playing.

### Expected behavior
1. No delay before the skip -> buffering -> playback sequence above. Correct behavior is also seen when jumping forward or back by 10 minutes (although the progress bar does not update correctly when jumping).

[Plex Media Player.log](https://github.com/plexinc/plex-media-player/files/3380360/Plex.Media.Player.log)

**Comment by celloch** [comment]
Same here. I had to downgrade to 2.35 to get proper behaviour without any delays.

**Comment by mseeley** [comment]
@pcalves this is related to another issue you're familiar with. Please adopt and close along with the other issue. Thanks!

**Comment by mseeley** [comment]
(This issue was closed automatically when the code fix was complete.)

**Comment by fetetert** [comment]
@mseeley , can this please be re-opened? The issue is still present on 2.38.

**Comment by pcalves** [comment]
Hey @fetetert, the fix will be included in the next release.

**Comment by fetetert** [comment]
Ah, Ok, thanks for the quick reply, I saw this issue was closed and a new client was released yesterday so I gave it a test.

I'll wait for the next release in that case. thanks.

**Comment by WayneD** [comment]
Sadly, it's not really fixed. The delay has been made smaller, but it's not back to normal yet. It also mishandles some skip situations, such as this one:

When starting to play a show that has an intro that is exactly 30 seconds long (e.g. Castle) I usually press 2 keys in quick succession: left-arrow then right-arrow. That way I end up exactly 30 seconds into the show. This no longer works (tested on 2.39.0) because a left skip pressed at less than 10 seconds into the show does nothing unless the input delay is allowed to expire.  Thus, I end up even further into the show because it doesn't even start the forward skip (only) until all the keyboard input is done.

I've also seen a weird situation when pressing left-arrow a few times in a row (deeper into a show) where the elapsed time does not keep going backward by 10 seconds, but instead skips around in a strange sequence. This failure is sporadic but easy to reproduce if you hit the left arrow at a varying cadence.

I'd really like to have it go back to immediate skipping like it was doing before, especially if the content is local (with both PMS and PMP on the same computer).

**Comment by humanthrope** [comment]
Also here to say that this hasn't been fixed in 2.39. But the 10 minute jump is working fine now.

**Comment by mseeley** [comment]
@pcalves checking in that 2.39 should contain the fix. Please advise + thanks!

**Comment by WayneD** [comment]
Sadly, several new releases later and the video skipping is still in a bad state. I have my main player update-blocked at 2.35 until this is resolved.  It's kinda looking like that's the last version of PMP I'll ever get.

**Comment by fetetert** [comment]
> 
> 
> Sadly, several new releases later and the video skipping is still in a bad state. I have my main player update-blocked at 2.35 until this is resolved. It's kinda looking like that's the last version of PMP I'll ever get.

I'm the same, I've stopped updates on all my HTPC's at 2.35.
