### ISSUE TITLE
Catch more exceptions in main()

### ISSUE THREAD

**Issue by elfring** [plexinc/plex-media-player#93]
I wonder why your function "[main](https://github.com/plexinc/plex-media-player/blob/3917405e4f809a3afeabada805fa43f92a8fce8b/src/main.cpp#L145 "main() function")" does not contain [catch clauses for more exception types](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108 "Uncaught exceptions") like they are described by Danny Kalev?

**Comment by wm4** [comment]
Yes, we throw only a very specific exception type, which we basically use to jump out of the main loop for some expected critical errors. I think it'd be too fragile to catch more exception types here, just to show our own message box.

But there's a good point here. Does our crash reporting catch uncaught exception properly, or what's going to show up as backtrace?

**Comment by elfring** [comment]
I suggest to consider another safety aspect which can depend on your preferred software build configuration eventually.
Do you care for implementation-defined behaviour from the general structure of your function "main"?

How do you think about to add the following items there?
* Catching [the exception "std::bad_alloc"](http://en.cppreference.com/w/cpp/memory/new/bad_alloc "Allocation failure") explicitly
* [Catch-all clause](http://en.cppreference.com/w/cpp/language/try_catch "try-block")

**Comment by wm4** [comment]
What dangers/safety aspects do you specifically have in mind?

**Comment by elfring** [comment]
Do you care if stack unwinding (and [execution of C++ object destructors](http://www.learncpp.com/cpp-tutorial/154-uncaught-exceptions-catch-all-handlers-and-exception-specifiers/#crayon-5633676f8d112855021558 "Reuse of catch-all handlers")) will be performed for your software finally?

**Comment by wm4** [comment]
Not really. Why would we? All I care is whether it shows up correctly in crash reports. (And of course, whether it really crashes in uncaught exceptions, instead of resuming some kind of zombie execution. I know some GUI frameworks catch exceptions in their mainloop and then ignore them, and that Windows allows you to ignore failed assertions. Scary stuff if you actually intend to find and fix bugs.)

**Comment by elfring** [comment]
Do any of your C++ object destructors perform valuable actions?

**Comment by wm4** [comment]
No.

**Comment by elfring** [comment]
I find this quick answer strange. Can C++ object destructors manage useful resources?

**Comment by wm4** [comment]
Uh, this is getting kind of philosophical, rather than being related to PMP.

Quick answer: since modern operating systems manage all resources of value, destructors rarely do anything useful on program exit, and you might as well exit immediately without running destructors (e.g. by using _exit).

I think with respect to PMP, this discussion is finished, so I'll close it.

**Comment by elfring** [comment]
I suggest to let each destructor perform its final action for the affected C++ objects.
I hope that the value of this service will not be underestimated.
