### ISSUE TITLE
Global : problems with product translation

### ISSUE THREAD

**Issue by Ribero** [plexinc/plex-media-player#934]
There is a real problem of taking into account translations made in transifex or incidents reported about translations. 
The reported incidents are systematically closed while the problems persist and are not taken into account. 
As an example, the last open incident on this subject (#922): was closed but not corrected. 

This situation gives the feeling that a correct and complete translation of the player is perceived as optional, not essential and may be not so important. 

If this is the case it is a pity but it's better to know it rather than expecting something that will not occur. Anyway, the correct and complete translation of Plex contributes greatly to the perception of quality by the customers (plex pass user) or any other users. 

In addition, translating is also sometimes a tedious work that becomes discouraging when it is not taken into account or is done too late. 

The purpose of this point is not to generate any controversy on the subject, but I prefer to ask openly about the status of translations:
- is the Plex project still interested in providing a correctly translated application?  Is it still wanted from users to contribute to the translations?
- why, when translations are available in transifex, are they not taken into account in the product?
- is there anything to be done or implemented - in addition to what is already available - to improve the situation? (If it is the will of the project).

Thanks in advance for the feedback

**Comment by mseeley** [comment]
> The purpose of this point is not to generate any controversy on the subject, but I prefer to ask openly about the status of translations:

Thanks for your thoughtful message. I'll address your comments/observations individually.

> The reported incidents are systematically closed while the problems persist and are not taken into account.
As an example, the last open incident on this subject (#922): was closed but not corrected.

It's a common practice to close issues when work directly related to that issue is complete instead of when the issue's fix has been released to the public. Translation issues resolve, on their own, in future releases as each release contains updated translations. This was explained: https://github.com/plexinc/plex-media-player/issues/922#issuecomment-564319550

> - is the Plex project still interested in providing a correctly translated application? Is it still wanted from users to contribute to the translations?

Yes, absolutely, on both questions.

> - why, when translations are available in transifex, are they not taken into account in the product?

A slice of translation data is retrieved from Transifex before each application update. Our applications do not download the latest translations automatically.

PMP is unique. The TV and Desktop layouts are individual consumers of translations. The TV layout is updated regularly; fresh translations are retrieved before each update. The Desktop layout has not been updated in quite a while. So, because translations are coupled to updates there are no translation changes in the Desktop layout.

The Desktop layout is also utilized on https://app.plex.tv, the non-PMP Desktop app, and bundled with PMS. We stagger releases to these different usages. The deployment at https://app.plex.tv updates most frequently.

> is there anything to be done or implemented - in addition to what is already available - to improve the situation? (If it is the will of the project).

Do you have specific suggestions that we should consider?

From my point of view, our translators may benefit from a better understanding of how translation changes reach end users. 

Besides that, I believe we're in an imperfect situation but we've made the correct trade offs for our concerns.

**Comment by mseeley** [comment]
Feel free to respond and we can continue to discuss.

**Comment by Ribero** [comment]
@mseeley Hi, sorry, I miss your answers.

PMP TV Layout (as explained in other issues) is not correctly transleted since months and at least 8 release (probably more).

> Translation issues resolve, on their own, in future releases as each release contains updated translations

Obviously, that not the reality. Something is broken in the translation process and strings that re taken into account in the Desktop layout and that should be identical in the TV Layout are left over. There nothing more to translate in transifex so the problem is probably not there.

I feel that the TV Layout just does not use the translated fields and, instead, only use the english one (only). Thay why the term "Library" is correctly translated in Desktop Layout in any supported language but stays at "Library" in TV Layout.

**Comment by mseeley** [comment]
I looked back through #922 and responded to each image. I didn't find any cases were TV and Desktop layouts were displaying the same string although untranslated in one or the other. Many of the strings you mentioned are strings provided by Plex Media Server, for example your "Library" observation.

Translation issues, in strings controlled by the Web Clients project in Transifex resolve, on their own, in future releases as each release contains updated translations. Invalid translations are ignored, for example the FR `Select {trackType} Track...` translation.

Strings provided by Plex Media Server should also resolve as they're updated between releases.

The reality is difficult, if not impossible, to understand entirely from the translators point of view.

**Comment by Ribero** [comment]
Thanks for taking time to answer.
