### ISSUE TITLE
Mac Desktop Player App - Download buttons missing

### ISSUE THREAD

**Issue by ssamulski** [plexinc/plex-media-player#958]
PMS Version:Mac Plex Server 1.19.1.2645
PMP Version:Mac Plex Player 1.8.2.1192-89432618

Steps to reproduce
1. Server and player are on the same network.
2. I am signed into the same account on both server and player. 
3. The top of my account page shows I have plexpass. 
4. Go to movie page and open menu 
5. Download button is missing where it should be above optimize. 

Current behavior
Download Buttons Are Missing. The download tab on the left if empty.

Expected behavior
I would expect download buttons like the support articles show. (https://support.plex.tv/articles/downloads-on-desktop/)

<img width="1280" alt="Screen Shot 2020-04-23 at 5 15 00 PM" src="https://user-images.githubusercontent.com/64230019/80151534-39ccf000-8588-11ea-8e8a-f92a5b05e1d5.png">
<img width="1281" alt="Screen Shot 2020-04-23 at 5 32 22 PM" src="https://user-images.githubusercontent.com/64230019/80151662-6e40ac00-8588-11ea-9227-035e8dc86307.png">

**Comment by ssamulski** [comment]
I have tested the Beta 3.104.2 and it no longer has this problem.

**Comment by nikonratm** [comment]
1.8.2.1192-89432618 is Plex for Mac _not_ PMP, no? And where did you get a beta build of the Mac app? I thought this repo is for PMP...

Same issue https://forums.plex.tv/t/desktop-players-download-button-missing-no-download-option/579136/15

**Comment by ssamulski** [comment]
I was mistaken about software versions. I was having problems with the Mac Plex App not Plex Media Player. The beta I spoke of was the preview posted on the forum. I guess maybe not actually BETA.

I was having problems with the Mac Plex App. It fixed itself over night.

Sorry for the confusion.

**Comment by mseeley** [comment]
It's totally okay @ssamulski. You're far from the only person that's reported issues using this repo. 

Earlier today a configuration issue was addressed that restored the Download link. It was a small change with a big effect. 😬 

Apologies for the issue + thanks for letting us know.

**Comment by nikonratm** [comment]
@mseeley Yes it is insanely confusing, especially because much of the documentation, forums etc. have not been properly updated. For example, if you go to the ["Desktop Player"](https://forums.plex.tv/c/plex-players/computers/34) area of the forums there is a stacked post from October 2018 (!) entitied ["Reporting Plex Media Player issues" ](https://forums.plex.tv/t/reporting-plex-media-player-issues/118566) that directs people to submit bugs here. There should be separate forums for PMP vs. Plex apps or at the very least the documentation there needs to be updated...

Anyway, was the "configuration issue" you mention described anywhere else? There is [a quite active thread in the forums](https://forums.plex.tv/t/desktop-players-download-button-missing-no-download-option/579136/21) and no reply from anyone "in the know", had to search high and low to find it here...

**Comment by mseeley** [comment]
Thanks for the feedback @nikonratm. Otto's in the know 👍 https://forums.plex.tv/t/desktop-players-download-button-missing-no-download-option/579136/19

**Comment by nikonratm** [comment]
Ah, I didn't realize, just seemed like a general "please restart" suggestion. Thanks

**Comment by mseeley** [comment]
(By the by we're following up on your feedback wrt to documentation. 😅)
