### ISSUE TITLE
Recently Added TV bugs

### ISSUE THREAD

**Issue by MollyBe** [plexinc/plex-media-player#973]
In the Recommended tab of a TV library there are two lists, Recently Aired TV and Recently Added TV. 

They both show:
- a poster
- the shows title
- the episode title
- the season and episode number

You can also click on each to go to their own page, there you can find four very noticeable differences/bugs:
1. On the Recently Aired TV page you can choose between Grid/List/Sumarry View, on the Recently Added TV page you cannot.
2. The Recently Added TV page is missing the shows title under the shows poster on every entry.
3. The Recently Added TV page is often missing season number episode numbers
4. The Recently Added TV page shows very few entries compared to The Recently Aired TV page, or even a Recently Added Movie page.

**Comment by mseeley** [comment]
I'll pass your message along although I am closing this issue as out of context for this repo. Please follow the issue reporting guidelines presented in the issue template.

**Comment by MollyBe** [comment]
I would rather this stay open but I understand it is a bug related to all players, where do you suggest I post this issue to keep it open?

**Comment by mseeley** [comment]
Issues can be mentioned in our forums. The moderators, ninjas, and employees will pass them along to us. This issue was closed because it didn't adhere to the issue reporting template. The template exists to guide and focus our discussions.

I appreciate you letting us know about this behavior. We worked on standardizing the title components as a result of your issue.
