### ISSUE TITLE
Google auth error

### ISSUE THREAD

**Issue by stevenhurwitt** [plexinc/plex-media-player#986]
Apologies if this is the wrong place. If it is - where should I submit a bug for Plex for Kindle Fire?

### Environment

Kindle Fire

### Steps to reproduce
1. Open Plex, attempt to sign in with Google oauth.

### Current behavior
1. Able to choose account but not complete sign in process. Hangs and does not complete authentication.

### Expected behavior
1. Authenticate so I can start watching!

**Comment by romancamelia** [comment]
Thanks for the report!
The fix is currently under review and most likely will go out with the 8.8 Android release.
Meanwhile, I suggest creating a Plex account with password using the same Google email address via web and login with Plex credentials on your Kindle Fire (It will actually be the same account as your Google one). Sorry for the inconvenience!
